sqlite:
  adapter: sqlite3
  database: tmp/data.sqlite3
  pool: 5
  timeout: 5000

mysql:
  adapter: mysql2
  database: lifetime_test
  pool: 5
  timeout: 5000
  username: root
  password:

postgresql:
  adapter: postgresql
  database: lifetime_test
  pool: 5
  timeout: 5000
  username: postgres
  password:
  min_messages: ERROR
